### ISSUE TITLE
Choosing your own avatar should open the camera, not Camera Roll

### ISSUE THREAD

**Issue by huyouare** [huyouare/Duke-Study-Group#3]

**Comment by huyouare** [comment]
I took another look at this @JustinLovesCompsci

**Comment by JustinLovesCompsci** [comment]
any problems? Basically I added a pop up bottom menu which has both camera and gallery button options for user to select from. Camera utilities may not work well. Will look into this later

**Comment by huyouare** [comment]
I fixed the camera utility.
