### ISSUE TITLE
Add Feedback Feature

### ISSUE THREAD

**Issue by huyouare** [huyouare/Duke-Study-Group#33]
https://github.com/rizumita/CTFeedback

**Comment by JustinLovesCompsci** [comment]
I am confused about how to use third party libraries from cocoapods. I added "pod 'CTFeedback'" to our podfile and run "pod install", but still cannot import CTFeedback into my classes. Do we still need to git cloning the repo and import into Xcode?

**Comment by JustinLovesCompsci** [comment]
@huyouare I imported CTFeedback via cocoapods, tried to send an email bug report but my email inbox never received it. Not sure if CTFeedback works. You may checkout branch feedback and pull the branch. I added a text button in Profile view for testing purposes (obviously we will change the UI). I just want to make sure that CTFeedback actually works. 

EDIT: Simulator does not have the default email application, so the feedback feature must be tested on an actual device.

**Comment by JustinLovesCompsci** [comment]
#57
