### ISSUE TITLE
Add more Loading HUDs, switch to more elegant framework

### ISSUE THREAD

**Issue by huyouare** [huyouare/Duke-Study-Group#49]
Add Loading HUDs in GroupSelectVC, GroupsVC, others

https://github.com/TransitApp/SVProgressHUD
https://github.com/pkluz/PKHUD

**Comment by JustinLovesCompsci** [comment]
@huyouare PKHUD swift code is outdated and does not compile correctly....I will use MBProgressHUD which is already in our repo

**Comment by JustinLovesCompsci** [comment]
This closes #65
