### ISSUE TITLE
Decide whether or not to use Duke Auth

### ISSUE THREAD

**Issue by huyouare** [huyouare/Duke-Study-Group#5]
If we launch this in Co-Lab App Store, it asks you to authenticate your NetID before you download. Therefore, we don't need to authenticate in our app. Right @JustinLovesCompsci?

**Comment by JustinLovesCompsci** [comment]
good point. just one quick question, if we launch in Co-Lab App store, will students be able to download on normal App store?

**Comment by huyouare** [comment]
We'd have to send it off to both places. We could theoretically make the
App Store version do Duke Auth (only once), but the co lab App Store works
pretty well.

**Comment by JustinLovesCompsci** [comment]
We all agreed on releasing the app only via Co-lab app store
