### ISSUE TITLE
Bug with photo selection

### ISSUE THREAD

**Issue by huyouare** [huyouare/Duke-Study-Group#7]
In Camera.swift utility function

**Comment by JustinLovesCompsci** [comment]
Do we still have the bug? I do not see anything wrong in selecting/sending a photo

**Comment by huyouare** [comment]
Yeah, I don't remember either, but I think the Video option doesn't work.

**Comment by JustinLovesCompsci** [comment]
ok I will close this one then. The video option is mentioned in another issue
